package net.tunamods.customglint.common.client;

import net.minecraft.server.packs.resources.ResourceManager;
import net.minecraft.server.packs.resources.ResourceManagerReloadListener;
import net.minecraftforge.client.event.RegisterClientReloadListenersEvent;
import net.minecraftforge.client.event.RenderLevelStageEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.tunamods.customglint.common.CustomGlintApiMod;

/**
 * Client-only initialization for {@code customglint_api}. Reached from
 * {@link CustomGlintApiMod#CustomGlintApiMod()} via {@code DistExecutor.safeRunWhenOn(Dist.CLIENT, ...)}
 * so the JVM never resolves {@link CustomGlintRenderer} or any client-only Forge event class on a
 * dedicated server.
 */
public final class CustomGlintClientInit {
    private CustomGlintClientInit() {}

    /** Invoked via {@code () -> CustomGlintClientInit::run} from the API mod constructor on client only. */
    public static void run() {
        FMLJavaModLoadingContext.get().getModEventBus().addListener(CustomGlintClientInit::onRegisterClientReloadListeners);
        // Glow-outline core shaders (silhouette + composite) — mod-bus event, client only.
        FMLJavaModLoadingContext.get().getModEventBus().addListener(GlowOutlineRenderer::registerShaders);
        // Procedural chromatic glint core shader — mod-bus event, client only.
        FMLJavaModLoadingContext.get().getModEventBus().addListener(CustomGlintRenderer::registerShaders);

        // Release the glow-outline offscreen target on resource reload so it isn't pinned for the session.
        CustomGlintRenderer.additionalReloadCleanup.add(GlowOutlineRenderer::release);

        // Once-per-frame reset. Arms the glint stencil masks (mount-armor glint via
        // forMountArmorStencilMask, Epic Knights decoration glint via the per-slot stencil pool) and
        // clears the glow-outline per-frame capture queue. RenderTickEvent.START fires once per rendered
        // frame regardless of shader pack or batched-render plumbing.
        MinecraftForge.EVENT_BUS.addListener((TickEvent.RenderTickEvent event) -> {
            if (event.phase == TickEvent.Phase.START) {
                CustomGlintRenderer.pendingFrameStencilClear = true;
                CustomGlintRenderer.resetStencilSlots();
                GlowOutlineRenderer.beginFrame();
            }
        });

        // Drain world-space item glow outlines after weather, where the live world projection / modelview
        // still match what the items were drawn with and the opaque scene depth is committed for the
        // occlusion test. Snapshot the world projection every frame here regardless — under a shader pack
        // the drain is DEFERRED to the RETURN of LevelRenderer.renderLevel (LevelRendererMixin), past which
        // the live projection has moved to GUI ortho; Iris composites its scene to the main target at that
        // RETURN, so a drain here would just be overwritten.
        MinecraftForge.EVENT_BUS.addListener((RenderLevelStageEvent event) -> {
            if (event.getStage() == RenderLevelStageEvent.Stage.AFTER_WEATHER) {
                GlowOutlineRenderer.snapshotWorldProjection();
                if (!CustomGlintRenderer.isShaderPackActive()) {
                    GlowOutlineRenderer.drainWorld();
                }
            }
        });
    }

    private static void onRegisterClientReloadListeners(RegisterClientReloadListenersEvent event) {
        // Anonymous class, not lambda: Forge's class transformer remaps method names (named→SRG)
        // at class-load time, but lambdas are generated by LambdaMetafactory at runtime and bypass
        // that transform — leaving the synthetic SAM named "onResourceManagerReload" while the
        // interface's abstract method at runtime is "m_6213_". That mismatch throws AbstractMethodError.
        event.registerReloadListener(new ResourceManagerReloadListener() {
            @Override
            public void onResourceManagerReload(ResourceManager manager) {
                CustomGlintRenderer.clearTextures();
            }
        });
    }
}
