package net.tunamods.customglint.common.client;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.ResourceManager;
import net.minecraft.server.packs.resources.ResourceManagerReloadListener;
import net.minecraftforge.client.event.RegisterClientReloadListenersEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.tunamods.customglint.common.CustomGlintApiMod;

/**
 * Client-only initialization for {@code customglint_api}. Reached from
 * {@link CustomGlintApiMod#CustomGlintApiMod()} via {@code DistExecutor.safeRunWhenOn(Dist.CLIENT, ...)}
 * so the JVM never resolves {@link CustomGlintRenderer} or any client-only Forge event class on a
 * dedicated server.
 */
public final class CustomGlintClientInit {
    private CustomGlintClientInit() {}

    /** Invoked via {@code () -> CustomGlintClientInit::run} from the API mod constructor on client only. */
    public static void run() {
        // Vanilla trident BEWLR outline texture: use the real trident texture so the outline
        // shader alpha-discards transparent texels instead of filling model cubes opaquely.
        CustomGlintRenderer.BEWLR_OUTLINE_TEXTURES.put(
                "net.minecraft.world.item.TridentItem",
                new ResourceLocation("minecraft", "textures/entity/trident.png"));

        FMLJavaModLoadingContext.get().getModEventBus().addListener(CustomGlintClientInit::onRegisterClientReloadListeners);

        // Once-per-frame stencil-clear gate reset. See pendingFrameStencilClear's javadoc
        // in CustomGlintRenderer for the multi-outline / FullyBuffered drain interaction
        // this prevents. RenderTickEvent.START fires once per rendered frame regardless of
        // shader pack or batched-render plumbing, which is what we need.
        MinecraftForge.EVENT_BUS.addListener((TickEvent.RenderTickEvent event) -> {
            if (event.phase == TickEvent.Phase.START) {
                CustomGlintRenderer.pendingFrameStencilClear = true;
                CustomGlintRenderer.shaderOutlinedThisFrame.clear();
                CustomGlintRenderer.resetStencilSlots();
                CustomGlintRenderer.resetStencilDiag();
                CustomGlintRenderer.probeFrameCounter++;
            }
        });
    }

    private static void onRegisterClientReloadListeners(RegisterClientReloadListenersEvent event) {
        // Anonymous class, not lambda: Forge's class transformer remaps method names (named→SRG)
        // at class-load time, but lambdas are generated by LambdaMetafactory at runtime and bypass
        // that transform — leaving the synthetic SAM named "onResourceManagerReload" while the
        // interface's abstract method at runtime is "m_6213_". That mismatch throws AbstractMethodError.
        event.registerReloadListener(new ResourceManagerReloadListener() {
            @Override
            public void onResourceManagerReload(ResourceManager manager) {
                CustomGlintRenderer.clearTextures();
            }
        });
    }
}
